# Permalinks
permalink:        pretty

# Setup
url:              http://qwtel.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Manvendra Singh

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  A software developer and a philanthropist from heart. Believes in humanity and 
  a worker for animal welfare.

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Manvendra Singh'
  twitter:        Manvendra_SK
  github:         manvendrask
  photo:          https://avatars0.githubusercontent.com/u/3501410

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Manvendra or [`@Manvendra_SK`](https://www.twitter.com/Manvendra_SK), which isn't an acronym.

    Read my thoughts on [#software and #technology](http://www.tothenew.com/blog/author/manvendra/).

    I'm a presently working for [SapientNitro](http://www.sapientnitro.com/en-us.html) as Tech Lead on [Node.js](https://nodejs.org) technology.
    Previously I was working with [TO THE NEW Digital](http://tothenew.com) as a Java professional.