# Permalinks
permalink:        pretty

# Setup
url:              http://qwtel.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Manvendra Singh

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  A pretentious two-column [Jekyll](http://jekyllrb.com/) theme, stolen by [@qwtel](https://twitter.com/qwtel)
  from [Hyde](http://hyde.getpoole.com).
  You could say it was.. [hydejacked](http://media3.giphy.com/media/makedRIckZBW8/giphy.gif).

# The tags listed as entries in the sidebar
sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Florian Klampfer'
  twitter:        Manvendra_SK
  github:         manvendrask
  photo:          https://avatars0.githubusercontent.com/u/3501410

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Florian or [`@qwtel`](https://www.twitter.com/qwtel), which isn't an acronym,
    I just [wanted a short username](http://qwtel.com/how-to-find-a-short-username) and that one happened to be available.

    Read my thoughts on [#software](http://qwtel.com/tag/software) and [#cryptoeconomics](http://qwtel.com/tag/cryptoeconomics).
