# Permalinks
permalink:        pretty

# Setup
url:              http://www.manvendrask.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          ''

title:            Manvendra Singh

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Philanthropist, Brother, Son, Friend, Mentor, Author and a Programmer.

# The tags listed as entries in the sidebar
sidebar_tags:     [javascript, jekyll]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Manvendra Singh'
  twitter:        Manvendra_SK
  github:         manvendrask
  photo:          /public/img/me.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    Hi, I'm Manvendra or [`@Manvendra_SK`](https://www.twitter.com/Manvendra_SK), which isn't an acronym, and that contains an *underscore* as Twitter needed it for its personal reasons.

    Read my thoughts on [#software](http://www.tothenew.com/blog/author/manvendra/) and [#technology](http://www.manvendrask.com).

    Presently I'm working for [TO THE NEW Digital](http://tothenew.com) as a Java professional.



  
# Presently I'm working for [SapientNitro](http://www.sapientnitro.com/en-us.html) as Tech Lead on [Node.js](https://nodejs.org) technology.
# Previously I was working with [TO THE NEW Digital](http://tothenew.com) as a Java professional.